### ISSUE TITLE
Not receiving data for 3 months

### ISSUE THREAD

**Issue by LoveMyData** [planningalerts-scrapers/botany_bay#2]
planningalerts-scrapers/botany_bay errored
It has been erroring for 3 months

/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/protocol.rb:158:in `rescue in rbuf_fill': too many connection resets (due to Net::ReadTimeout - Net::ReadTimeout) after 0 requests on 69924164958340, last used 1473612730.5438242 seconds ago (Net::HTTP::Persistent::Error)
    from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/protocol.rb:152:in`rbuf_fill'
    from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/protocol.rb:134:in `readuntil'
    from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/protocol.rb:144:in`readline'
    from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http/response.rb:39:in `read_status_line'(truncated)

**Comment by LoveMyData** [comment]
Code updated, pending for PR approval

**Comment by LoveMyData** [comment]
fixed with https://github.com/planningalerts-scrapers/botany_bay/commit/701a9b768eaa0aaf5bb0ab2642c2b7a3b67300c4
